### ISSUE TITLE
The Pushe service notification is not available....

### ISSUE THREAD

**Issue by h2soheili** [pusheco/pushe-react-native#17]
`"pushe-react-native": "^2.0.2",
    "react": "^16.11.0",
    "react-native": "^0.62.2",`

`The Pushe service notification is not available. This either means you have provided an invalid Pushe Service name, Pushe was not initialized successfully or you have not added the Pushe service to your gradle dependencies.
2020-04-26 12:33:34.542 16660-16705/com.daapapp E/Pushe: The Pushe service analytics is not available. This either means you have provided an invalid Pushe Service name, Pushe was not initialized successfully or you have not added the Pushe service to your gradle dependencies.
2020-04-26 12:33:34.542 16660-16705/com.daapapp E/Pushe: The Pushe service notification is not available. This either means you have provided an invalid Pushe Service name, Pushe was not initialized successfully or you have not added the Pushe service to your gradle dependencies.
2020-04-26 12:33:34.543 16660-16705/com.daapapp E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void co.pushe.plus.notification.PusheNotification.setNotificationListener(co.pushe.plus.notification.PusheNotificationListener)' on a null object reference
        at co.pushe.plus.RNPushe.initializeNotificationCallbacks(RNPushe.java:401)
        at co.pushe.plus.RNPushe.<init>(RNPushe.java:71)
        at co.pushe.plus.RNPushePackage.createNativeModules(RNPushePackage.java:17)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1298)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1269)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1194)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:132)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:996)
        at java.lang.Thread.run`

نام اپ و کلید درست جایگذاری شده و در لاگ کت هم خروجی میده.

**Comment by fsghasemi** [comment]
موقعی که اپتون رو اجرا میکنید این خطا رو میگیرد درسته؟ خروجی بعد از اجرای دستور npm i -P pushe-react-native
 چی بوده؟

**Comment by h2soheili** [comment]
مث نصب  هر پکیج دیگه ای نصب شد .
این خروجی بالا بعد ران اپ هست که از لاگ کت بردشاتم .دستی هم لینک کردم .سینک شد و کامپایل شد.

**Comment by h2soheili** [comment]
pushe-react-native  به جای
میشه از نسخه قدیمی 
react-native-pushe
استفاده کرد؟
مشکل گریدل یا تناقض با نسخه جدید ری اکت رو تو نسخه قبل درست کردید که اون رو هم تست کنم ؟

**Comment by h2soheili** [comment]
```
implementation project(':pushe-react-native')

include ':pushe-react-native'
project(':pushe-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/pushe-react-native/android')

import co.pushe.plus.RNPushePackage;
 packages.add(new RNPushePackage());

<meta-data android:name="co.ronash.pushe.token" android:value=""/>
```

**Comment by amirhaa** [comment]
<div dir="rtl">
سلام

کتابخانه پوشه با پکیج نیم ‍‍~~react-native-pushe~~ دیگه deprecate شده و قابل استفاده نمی‌باشد و
باید از **[pushe-react-native](https://www.npmjs.com/package/pushe-react-native)** استفاده کنید.

اما مشکل لینک نشدن کتابخانه احتمالا از خود کتابخانه نمی باشد و ما در تست های خودمان همچین مشکلی نداشتیم. البته در نسخه های قبل از 0.60 ری اکت که می بایست از دستور `react-native link` استفاده کرد برای یک کاربر این مورد اتفاق افتاده بود ولی بعد از آن دیگه این مورد را نداشتیم

**برای سینک شدن گریدل هم باید  ابزار گذر از تحریم داشته باشید.**


فقط برخی مواقع در آپدیت نسخه های کتابخانه ممکنه گردیل نتواند پیش نیازهای پوشه را بگیرد که در این مواقع باید کش گریدل را پاک کرد

امکانش هست منظورتان از تناقض با نسخه جدید ری‌اکت را بیشتر توضیح دهید؟
</div>

**Comment by h2soheili** [comment]
با اندروید استودو و گریدل غریبه نیستم.
پروژه خام هم تست کردم ولی نشد.
حتی پروژه سمپل خودتون رو تست کردم که باز همون ارور رو داد که البته 
`<meta-data android:name="co.ronash.pushe.token" android:value=""/>
`با 
پروژه سمپل فرق داره.
در کل یک انسجام در دایکیومنت ها وکتابخونه از نظر ورژن بندی نیس..
اگر امکانش باشه پروژه سمپل رو برای تست بالا بیارید . تا اگر اوکی نبود خودتون ایراد رو ببینید.

منظور از تناقض  . شاید به خاطر 
`lazy load 
`نتیو ماژول باشه .
قرار بود که پکیج های نتیو هم در ری اکت موقع استفاده لود بشن.
در مورد فعال بودن در این نسخه ۰.۶۲ مطمئن نیستم

**Comment by h2soheili** [comment]
مشکل از این یه خط بود.
هم کلید ایراد داشت و هم مقدار.
الان اکیه. .
`<meta-data android:name="pushe_token" android:value="کلید"/>`

ممنون
