### ISSUE TITLE
E/Pushe: Error trying to retrieve fragment's id name. Ignoring the fragment

### ISSUE THREAD

**Issue by h2soheili** [pusheco/pushe-react-native#18]
ارور پایین به مراتب پرینت میشه و چند جا باعث کرش شده.

`"pushe-react-native": "^2.0.2","react": "^16.11.0","react-native": "^0.62.2",`

```
No package identifier when getting name for resource number 0x000001dd
2020-04-27 19:03:30.206 2486-2486/com.daapapp E/Pushe: Error trying to retrieve fragment's id name. Ignoring the fragment
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x1dd
        at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:252)
        at android.content.res.Resources.getResourceEntryName(Resources.java:1941)
        at co.pushe.plus.analytics.a.b(AppLifecycleListener.kt:107)
        at co.pushe.plus.analytics.a.a(AppLifecycleListener.kt:20)
        at co.pushe.plus.analytics.a$d.apply(AppLifecycleListener.kt:1053)
        at io.reactivex.internal.d.e.au$a.onNext(Unknown Source)
        at co.pushe.plus.utils.rx.BehaviorRelay$BehaviorDisposable.test(BehaviorRelay.java:366)
        at co.pushe.plus.utils.rx.BehaviorRelay$BehaviorDisposable.emitNext(BehaviorRelay.java:360)
        at co.pushe.plus.utils.rx.BehaviorRelay.accept(BehaviorRelay.java:137)
        at co.pushe.plus.analytics.c.onFragmentResumed(AppLifecycleNotifier.kt:1038)
        at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentResumed(FragmentLifecycleCallbacksDispatcher.java:207)
        at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentResumed(FragmentLifecycleCallbacksDispatcher.java:203)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:374)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2007)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
بعید می‌دونم این خطا باعث کرش باشه
این پیام مربوط به سرویس آنالیتیکس هست که flowی کار با اپلیکیشن رو track می‌کنه. در صورتی که فرگمنت رو نتونه track کنه یه پیام ارور چاپ می‌کنه. با توجه به اینکه فریم‌ورک ری‌اکت نیتیو استفاده شده می‌تونید این پیام رو نادیده بگیرید.

در صورتی که برنامه کرش می‌کنه دلیلش چیز دیگه‌ای باید باشه و این بخش نیست. لطفا مجددا استک‌تریس رو بررسی کنید و ببینید آیا خطای دیگه‌ای هست توی این موضوع.

(این رو هم در نظر داشته باشید در صورتی که لایبرری کرش داخلی داشته باشه اون کرش به لایه‌ی بالاتر منتقل نمیشه و اپ بسته نمیشه)

</div>

**Comment by h2soheili** [comment]
کجا داکیومنت فعال سازی یا غیر فعال سازی سرویس آنالیتسکس رو گذاشتید؟
اصلا قابلیت رو داره ؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

برای این کار بایستی کد پلاگین رو ادیت کنید و گریدل اون رو تغییر بدید.
[شخصی‌سازی ماژول‌های SDK](http://docs.pushe.co/docs/android-studio/advanced-setup#%D8%B4%D8%AE%D8%B5%DB%8C%D8%B3%D8%A7%D8%B2%DB%8C-%D9%85%D8%A7%DA%98%D9%88%D9%84%D9%87%D8%A7%DB%8C-sdk)

همچنین می‌تونید اون رو از بیس که به گریدل اضافه می‌کنید جدا کنید (با در نظر گرفتن اینکه فیچرهایی وابسته به آنالیتیکس رو نخواهید داشت. مثل Automation و Segmentation و ...)
</div>

```groovy
implementation ("co.pushe.plus:base:$latest") {
        exclude group: 'co.pushe.plus', module: 'analytics'
}
```

**Comment by h2soheili** [comment]
با اضافه کردن این خط به جای دیفالت

```
implementation ("co.pushe.plus:base:2.0.4") {
        exclude group: 'co.pushe.plus', module: 'analytics'
    }
```

و چند جا کامنت کردن آنالیتکس . دیگه ارور نداریم . اگر این باگ رو رفع کنید هر چه زودتر عالی میشه تا در نسخه پروداکشن هم آنالیتیکس باشه.
ممنون از زحمات
