### ISSUE TITLE
how to fix Pushe: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String ?

### ISSUE THREAD

**Issue by emami7495** [pusheco/pushe-react-native#28]
Hi we integrated 'pushe-react-native' in our react native project and get this error on android studio logcat and sentry 

`Pushe: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at com.squareup.moshi.StandardJsonAdapters$10.toJson(StandardJsonAdapters.java:213)
        at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:144)
        at com.squareup.moshi.MapJsonAdapter.toJson(MapJsonAdapter.java:58)
        at com.squareup.moshi.MapJsonAdapter.toJson(MapJsonAdapter.java:30)
        at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:144)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:52)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:58)
        at co.pushe.plus.utils.PusheStorage$StoredMap.performSave(PusheStorage.kt:619)
        at co.pushe.plus.utils.PusheStorage$1.invoke(PusheStorage.kt:526)
        at co.pushe.plus.utils.PusheStorage$1.invoke(PusheStorage.kt:1)
        at co.pushe.plus.utils.rx.RxUtilsKt$keepDoing$2.accept(RxUtils.kt:1)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onNext(ObservableOnErrorNext.java:68)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:101)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at co.pushe.plus.m0.c$a.run(Schedulers.kt:3)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)`

**Comment by mahdi-malv** [comment]
Hey

Are you somehow overriding `moshi` library in your project?

**Comment by emami7495** [comment]
No, is it possible we used another library that cause the problem?
If having a file like build.gradle or package.json can help, I can share them

**Comment by mahdi-malv** [comment]
If you could find the cause of the library in `gradlew help:dependencies` gradle task, that would be helpful

Try opening `project_root/android` folder using `android studio` (or `studio . ` via command line) and run this task

**Comment by mahdi-malv** [comment]
Inactive for a few months. Please re-open if the problem still exists
